pipeline {
    agent any

    tools {
        maven "Maven"
        jdk "JDK17"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean compile package -f ./devopsrepo/numbers-proj/pom.xml'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -f ./devopsrepo/numbers-proj/pom.xml'
            }
            post {
                always {
                    archiveArtifacts '**/*.jar'
                }
            }
        }
    }
}
